# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rec_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rec_item_widget(object):
    def setupUi(self, rec_item_widget):
        rec_item_widget.setObjectName("rec_item_widget")
        rec_item_widget.resize(100, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rec_item_widget.sizePolicy().hasHeightForWidth())
        rec_item_widget.setSizePolicy(sizePolicy)
        rec_item_widget.setMinimumSize(QtCore.QSize(100, 160))
        rec_item_widget.setMaximumSize(QtCore.QSize(100, 160))
        self.frame_33 = QtWidgets.QFrame(rec_item_widget)
        self.frame_33.setGeometry(QtCore.QRect(0, 0, 100, 162))
        self.frame_33.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_33.setMaximumSize(QtCore.QSize(100, 162))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_41 = QtWidgets.QFrame(self.frame_33)
        self.frame_41.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_41.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_2 = QtWidgets.QLabel(self.frame_41)
        self.label_2.setMinimumSize(QtCore.QSize(78, 50))
        self.label_2.setMaximumSize(QtCore.QSize(78, 50))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_22.addWidget(self.label_2)
        self.verticalLayout_18.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.frame_33)
        self.frame_42.setMinimumSize(QtCore.QSize(0, 90))
        self.frame_42.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_3 = QtWidgets.QLabel(self.frame_42)
        self.label_3.setMinimumSize(QtCore.QSize(78, 70))
        self.label_3.setMaximumSize(QtCore.QSize(78, 70))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_21.addWidget(self.label_3)
        self.verticalLayout_18.addWidget(self.frame_42)

        self.retranslateUi(rec_item_widget)
        QtCore.QMetaObject.connectSlotsByName(rec_item_widget)

    def retranslateUi(self, rec_item_widget):
        _translate = QtCore.QCoreApplication.translate
        rec_item_widget.setWindowTitle(_translate("rec_item_widget", "Form"))
        self.label_2.setText(_translate("rec_item_widget", "상호명"))
        self.label_3.setText(_translate("rec_item_widget", "주소"))
