# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/first_trip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first_trip(object):
    def setupUi(self, first_trip):
        first_trip.setObjectName("first_trip")
        first_trip.resize(1000, 700)
        first_trip.setMinimumSize(QtCore.QSize(1000, 700))
        first_trip.setMaximumSize(QtCore.QSize(1000, 700))
        self.label = QtWidgets.QLabel(first_trip)
        self.label.setGeometry(QtCore.QRect(410, 330, 56, 12))
        self.label.setObjectName("label")

        self.retranslateUi(first_trip)
        QtCore.QMetaObject.connectSlotsByName(first_trip)

    def retranslateUi(self, first_trip):
        _translate = QtCore.QCoreApplication.translate
        first_trip.setWindowTitle(_translate("first_trip", "Form"))
        self.label.setText(_translate("first_trip", "frist_trip"))
