# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/location_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_location_item(object):
    def setupUi(self, location_item):
        location_item.setObjectName("location_item")
        location_item.resize(410, 100)
        location_item.setMinimumSize(QtCore.QSize(410, 100))
        location_item.setMaximumSize(QtCore.QSize(410, 100))
        location_item.setStyleSheet("#frame_2{\n"
"background-color:#a20402;\n"
"}\n"
"#label_name{\n"
"color: #e8eff0;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(location_item)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(location_item)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_name = QtWidgets.QLabel(self.frame_2)
        self.label_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(14)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_2.addWidget(self.label_name)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(9, 3, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_adress = QtWidgets.QLabel(self.frame_3)
        self.label_adress.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(11)
        self.label_adress.setFont(font)
        self.label_adress.setObjectName("label_adress")
        self.verticalLayout_3.addWidget(self.label_adress)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(location_item)
        QtCore.QMetaObject.connectSlotsByName(location_item)

    def retranslateUi(self, location_item):
        _translate = QtCore.QCoreApplication.translate
        location_item.setWindowTitle(_translate("location_item", "Form"))
        self.label_name.setText(_translate("location_item", "광주인력개발원"))
        self.label_adress.setText(_translate("location_item", "광주광역시 광산구 소촌로 152번길 37"))
