# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/location_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_location_item(object):
    def setupUi(self, location_item):
        location_item.setObjectName("location_item")
        location_item.resize(110, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(location_item.sizePolicy().hasHeightForWidth())
        location_item.setSizePolicy(sizePolicy)
        location_item.setMinimumSize(QtCore.QSize(110, 150))
        location_item.setMaximumSize(QtCore.QSize(110, 150))
        self.verticalLayout = QtWidgets.QVBoxLayout(location_item)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(location_item)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_adress = QtWidgets.QLabel(self.frame)
        self.label_adress.setGeometry(QtCore.QRect(20, 40, 56, 12))
        self.label_adress.setObjectName("label_adress")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(location_item)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_name = QtWidgets.QLabel(self.frame_2)
        self.label_name.setGeometry(QtCore.QRect(20, 20, 56, 12))
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(location_item)
        QtCore.QMetaObject.connectSlotsByName(location_item)

    def retranslateUi(self, location_item):
        _translate = QtCore.QCoreApplication.translate
        location_item.setWindowTitle(_translate("location_item", "Form"))
        self.label_adress.setText(_translate("location_item", "TextLabel"))
        self.label_name.setText(_translate("location_item", "TextLabel"))
