# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/recommended_place.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recommended_place(object):
    def setupUi(self, recommended_place):
        recommended_place.setObjectName("recommended_place")
        recommended_place.resize(1000, 700)
        recommended_place.setMinimumSize(QtCore.QSize(1000, 700))
        recommended_place.setMaximumSize(QtCore.QSize(1000, 700))
        self.label = QtWidgets.QLabel(recommended_place)
        self.label.setGeometry(QtCore.QRect(440, 340, 191, 51))
        self.label.setObjectName("label")

        self.retranslateUi(recommended_place)
        QtCore.QMetaObject.connectSlotsByName(recommended_place)

    def retranslateUi(self, recommended_place):
        _translate = QtCore.QCoreApplication.translate
        recommended_place.setWindowTitle(_translate("recommended_place", "Form"))
        self.label.setText(_translate("recommended_place", "recommend"))
