# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/recall_previous_trip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recall_proevious_trip(object):
    def setupUi(self, recall_proevious_trip):
        recall_proevious_trip.setObjectName("recall_proevious_trip")
        recall_proevious_trip.resize(1000, 700)
        recall_proevious_trip.setMinimumSize(QtCore.QSize(1000, 700))
        recall_proevious_trip.setMaximumSize(QtCore.QSize(1000, 700))
        self.label = QtWidgets.QLabel(recall_proevious_trip)
        self.label.setGeometry(QtCore.QRect(410, 320, 56, 12))
        self.label.setObjectName("label")

        self.retranslateUi(recall_proevious_trip)
        QtCore.QMetaObject.connectSlotsByName(recall_proevious_trip)

    def retranslateUi(self, recall_proevious_trip):
        _translate = QtCore.QCoreApplication.translate
        recall_proevious_trip.setWindowTitle(_translate("recall_proevious_trip", "Form"))
        self.label.setText(_translate("recall_proevious_trip", "recall_pr"))
