# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1120, 497)
        main.setAcceptDrops(True)
        main.setStyleSheet("* {\n"
"    font: 12pt \"강원특별자치도체 SemiBold\";\n"
"}\n"
"QListWidget\n"
"{\n"
"border : 2px solid black;\n"
"background : lightgreen;\n"
"}\n"
"QListWidget QScrollBar\n"
"{\n"
"background : lightblue;\n"
"}\n"
" QListView::item:selected\n"
"{\n"
"border : 2px solid black;\n"
"background : green;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_banner = QtWidgets.QWidget(main)
        self.widget_banner.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_banner.setMaximumSize(QtCore.QSize(80, 16777215))
        self.widget_banner.setObjectName("widget_banner")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_banner)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_1 = QtWidgets.QPushButton(self.widget_banner)
        self.btn_1.setObjectName("btn_1")
        self.verticalLayout.addWidget(self.btn_1)
        self.btn_2 = QtWidgets.QPushButton(self.widget_banner)
        self.btn_2.setObjectName("btn_2")
        self.verticalLayout.addWidget(self.btn_2)
        self.btn_3 = QtWidgets.QPushButton(self.widget_banner)
        self.btn_3.setObjectName("btn_3")
        self.verticalLayout.addWidget(self.btn_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget_banner)
        self.widget = QtWidgets.QWidget(main)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(main)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(600, 16777215))
        self.stackedWidget_2.setAcceptDrops(True)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_3.addWidget(self.calendarWidget)
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.page_2)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.horizontalLayout_3.addWidget(self.calendarWidget_2)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setAcceptDrops(True)
        self.page.setObjectName("page")
        self.listWidget = QtWidgets.QListWidget(self.page)
        self.listWidget.setGeometry(QtCore.QRect(40, 30, 256, 192))
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listView = QtWidgets.QListView(self.page)
        self.listView.setGeometry(QtCore.QRect(50, 240, 256, 192))
        self.listView.setDragEnabled(True)
        self.listView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listView.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listView.setObjectName("listView")
        self.stackedWidget_2.addWidget(self.page)
        self.stackedWidget_2Page1 = QtWidgets.QWidget()
        self.stackedWidget_2Page1.setObjectName("stackedWidget_2Page1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.stackedWidget_2Page1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.stackedWidget_2Page1)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_location_1 = QtWidgets.QPushButton(self.widget_4)
        self.btn_location_1.setObjectName("btn_location_1")
        self.verticalLayout_2.addWidget(self.btn_location_1)
        self.btn_location_2 = QtWidgets.QPushButton(self.widget_4)
        self.btn_location_2.setObjectName("btn_location_2")
        self.verticalLayout_2.addWidget(self.btn_location_2)
        self.btn_location_3 = QtWidgets.QPushButton(self.widget_4)
        self.btn_location_3.setObjectName("btn_location_3")
        self.verticalLayout_2.addWidget(self.btn_location_3)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.stackedWidget_2Page1)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_show_banner = QtWidgets.QPushButton(self.widget_5)
        self.btn_show_banner.setObjectName("btn_show_banner")
        self.verticalLayout_3.addWidget(self.btn_show_banner)
        self.btn_hide_banner = QtWidgets.QPushButton(self.widget_5)
        self.btn_hide_banner.setObjectName("btn_hide_banner")
        self.verticalLayout_3.addWidget(self.btn_hide_banner)
        self.horizontalLayout_2.addWidget(self.widget_5)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.stackedWidget_2.addWidget(self.stackedWidget_2Page1)
        self.horizontalLayout.addWidget(self.stackedWidget_2)

        self.retranslateUi(main)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Form"))
        self.btn_1.setText(_translate("main", "1"))
        self.btn_2.setText(_translate("main", "2"))
        self.btn_3.setText(_translate("main", "3"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("main", "아이템1"))
        item = self.listWidget.item(1)
        item.setText(_translate("main", "아이템2"))
        item = self.listWidget.item(2)
        item.setText(_translate("main", "아이템3"))
        item = self.listWidget.item(3)
        item.setText(_translate("main", "아이템4"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.btn_location_1.setText(_translate("main", "Location_1"))
        self.btn_location_2.setText(_translate("main", "Location_2"))
        self.btn_location_3.setText(_translate("main", "Location_3"))
        self.btn_show_banner.setText(_translate("main", "show_banner"))
        self.btn_hide_banner.setText(_translate("main", "hide_banner"))
