# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/select_schedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_schedule(object):
    def setupUi(self, select_schedule):
        select_schedule.setObjectName("select_schedule")
        select_schedule.resize(1000, 700)
        select_schedule.setMinimumSize(QtCore.QSize(1000, 700))
        select_schedule.setMaximumSize(QtCore.QSize(1000, 700))
        self.label = QtWidgets.QLabel(select_schedule)
        self.label.setGeometry(QtCore.QRect(560, 400, 161, 51))
        self.label.setObjectName("label")

        self.retranslateUi(select_schedule)
        QtCore.QMetaObject.connectSlotsByName(select_schedule)

    def retranslateUi(self, select_schedule):
        _translate = QtCore.QCoreApplication.translate
        select_schedule.setWindowTitle(_translate("select_schedule", "Form"))
        self.label.setText(_translate("select_schedule", "schedule"))
