# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/select_place_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_place_list(object):
    def setupUi(self, select_place_list):
        select_place_list.setObjectName("select_place_list")
        select_place_list.resize(1000, 700)
        select_place_list.setMinimumSize(QtCore.QSize(1000, 700))
        select_place_list.setMaximumSize(QtCore.QSize(1000, 700))
        self.label = QtWidgets.QLabel(select_place_list)
        self.label.setGeometry(QtCore.QRect(490, 360, 56, 12))
        self.label.setObjectName("label")

        self.retranslateUi(select_place_list)
        QtCore.QMetaObject.connectSlotsByName(select_place_list)

    def retranslateUi(self, select_place_list):
        _translate = QtCore.QCoreApplication.translate
        select_place_list.setWindowTitle(_translate("select_place_list", "Form"))
        self.label.setText(_translate("select_place_list", "place_list"))
