# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/save_schedule_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_save_schedule_item(object):
    def setupUi(self, save_schedule_item):
        save_schedule_item.setObjectName("save_schedule_item")
        save_schedule_item.resize(528, 100)
        save_schedule_item.setMinimumSize(QtCore.QSize(528, 100))
        save_schedule_item.setMaximumSize(QtCore.QSize(528, 100))
        self.verticalLayout = QtWidgets.QVBoxLayout(save_schedule_item)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(save_schedule_item)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_schedule_name = QtWidgets.QLabel(self.frame_2)
        self.label_schedule_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(14)
        self.label_schedule_name.setFont(font)
        self.label_schedule_name.setObjectName("label_schedule_name")
        self.horizontalLayout.addWidget(self.label_schedule_name)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_date = QtWidgets.QLabel(self.frame_3)
        self.label_date.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(11)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.horizontalLayout_2.addWidget(self.label_date)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(save_schedule_item)
        QtCore.QMetaObject.connectSlotsByName(save_schedule_item)

    def retranslateUi(self, save_schedule_item):
        _translate = QtCore.QCoreApplication.translate
        save_schedule_item.setWindowTitle(_translate("save_schedule_item", "Form"))
        self.label_schedule_name.setText(_translate("save_schedule_item", "여행 제목"))
        self.label_date.setText(_translate("save_schedule_item", "yyyy.mm.dd ~ yyyy.mm.dd"))
